plugins {
    id 'java-library'
    id 'io.papermc.paperweight.userdev' version '2.0.0-beta.21'
    id 'xyz.jpenilla.run-paper' version '3.0.2'
}

group = 'com.github.darksoulq'
version = '1.9.4-mc.26.1.2'

def targetJavaVersion = 25

java {
    toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
}

repositories {
    mavenCentral()

    maven {
        name = 'papermc-repo'
        url = uri('https://repo.papermc.io/repository/maven-public/')
    }

    maven {
        name = 'sonatype'
        url = uri('https://oss.sonatype.org/content/groups/public/')
    }

    // PlaceholderAPI
    maven {
        name = 'placeholderapi'
        url = uri('https://repo.extendedclip.com/releases/')
    }
}

dependencies {
    paperweight.paperDevBundle('26.1.2.build.12-alpha')
    compileOnly 'me.clip:placeholderapi:2.11.6'
}

runPaper.folia.registerTask()

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release.set(targetJavaVersion)
}

tasks.named('runServer') {
    minecraftVersion('26.1.2')
    jvmArgs '-Xms2G', '-Xmx2G', '-Dcom.mojang.eula.agree=true'
}

tasks.named('runFolia') {
    minecraftVersion('26.1.2')
    jvmArgs '-Xms2G', '-Xmx2G', '-Dcom.mojang.eula.agree=true'
}

tasks.named('processResources') {
    def props = [version: version]

    inputs.properties(props)
    filteringCharset = 'UTF-8'

    filesMatching('paper-plugin.yml') {
        expand(props)
    }
}