name: WIT
version: '1.9.5-mc.26.2'
main: com.github.darksoulq.wit.WIT
api-version: '26.2'
authors:
  - DarkSoul

folia-supported: true

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
