name: WIT
version: '1.9.3-mc.1.21.11'
main: com.github.darksoulq.wit.WIT
api-version: '1.21.11'
authors:
  - DarkSoul

folia-supported: true

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
