name: WhatIsThat
version: '1.4.0'
main: me.darksoul.whatIsThat.WhatIsThat
api-version: '1.20'

softdepend:
  - Minetorio
  - ItemsAdder
  - LoneLibs
  - ValhallaMMO
  - AuraMobs
  - AuraSkills
  - EliteMobs
  - Slimefun
  - LiteFarm
  - Nexo

commands:
  wit:
    description: Main command for WhatIsThat plugin.
    usage: /wit [disable|enable]
    permission: wit.toggledisplay
    aliases:
      - whatisthat