name: WhatIsThat
version: '1.3.1'
main: me.darksoul.whatIsThat.WhatIsThat
api-version: '1.21'

softdepend:
  - Minetorio
  - ItemsAdder
  - LoneLibs

commands:
  wit:
    description: Main command for WhatIsThat plugin.
    usage: /wit [disable|enable]
    permission: wit.toggledisplay
    aliases:
      - whatisthat