name: WhatIsThat
version: '1.0'
main: me.darksoul.whatIsThat.WhatIsThat
api-version: '1.21'

softdepend:
  - Minetorio

commands:
  wit:
    description: Main command for WhatIsThat plugin.
    usage: /wit [disable|enable]
    permission: wit.toggledisplay
    aliases:
      - whatisthat