SPLITTER: " <white>|</white> "

minecraft:
  # Prefixes
  items_in_container: "<gold>📦 <items></gold> "
  entity_owner: "<gray><entity_owner></gray> "
  entity_is_leashed: "<leash_icon> "
  # Suffixes
  farmland_hydrated: " <blue>\uD83D\uDCA7</blue>"
  farmland_not_hydrated: " <gray>\uD83D\uDCA7</gray>"
  redstone_power_level: " <red>● <power></red>"
  redstone_power_on: " <red>●</red>"
  redstone_power_off: " <gray>●</gray>"
  crop_age_1: " <color_by_percent>\uD83C\uDF31 <age>/<max_age><color_by_percent_end>"
  crop_age_2: " <color_by_percent>🌿 <age>/<max_age><color_by_percent_end>"
  crop_age_3: " <color_by_percent>🌽 <age>/<max_age><color_by_percent_end>"
  crop_age_4: " <color_by_percent>🌽 <age>/<max_age><color_by_percent_end>"
  honey_level: " <honey_icon> <color_by_percent><honey_level>/<honey_max_level><color_by_percent_end>"
  smelt_time: " <color_by_percent>⌛ <seconds_remaining>s<color_by_percent_end>"
  beacon_1_effect: " <effect_icon> <primary_amplifier>"
  beacon_2_effect: " <effect_icon_1> <primary_amplifier> <effect_icon_2> <secondary_amplifier>"
  spawner_info: " <egg_icon> <green><spawning_entity></green>"
  noteblock_info: " <gold>🎹 <instrument>: <tone> <octave></gold>"
  entity_time_to_grow: " <entity_egg> <yellow><seconds_left>s</yellow>"
  entity_health: " <heart_icon> <red><entity_health>/<entity_max_health></red>"
  villager_profession: " <gray><profession></gray>"
  tnt_fuse_time: " <red>\uD83D\uDCA3<fuse_time></red>"
  horse_speed: " <speed_icon> <horse_speed>"
  horse_jump_strength: " <jump_icon> <horse_jump_strength>"

percent_color:
  25: "<red>"
  50: "<yellow>"
  75: "<green>"
  100: "<dark_green>"
  default: "<gray>"

profession:
  # Suffixes
  ARMORER: " Armorer"
  BUTCHER: " Butcher"
  CARTOGRAPHER: " Cartographer"
  CLERIC: " Cleric"
  FARMER: " Farmer"
  FISHERMAN: " Fisherman"
  FLETCHER: " Fletcher"
  LEATHER_WORKER: " Leather Worker"
  LIBRARIAN: " Librarian"
  MASON: " Mason"
  NITWIT: " Nitwit"
  SHEPHERD: " Shepherd"
  JOBLESS: " Jobless"
